import { Router } from "express";
import { usersRouter } from "./users";
import { projectsRouter } from "./projects";
import { tasksRouter } from "./tasks";
import { commentsRouter } from "./comments";
import { dashboardRouter } from "./dashboard";
import { notificationsRouter } from "./notifications";
import { reportsRouter } from "./reports";
import { formsRouter } from "./forms";
import { automationsRouter } from "./automations";
import { aiRouter } from "./ai";
import { apiTokensRouter } from "./apiTokens";
import { webhooksRouter } from "./webhooks";
import { externalRouter } from "./external";

export const router = Router();

router.use("/users", usersRouter);
router.use("/projects", projectsRouter);
router.use("/tasks", tasksRouter);
router.use("/comments", commentsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/notifications", notificationsRouter);
router.use("/reports", reportsRouter);
router.use("/forms", formsRouter);
router.use("/automations", automationsRouter);
router.use("/ai", aiRouter);
router.use("/api-tokens", apiTokensRouter);
router.use("/webhooks", webhooksRouter);
router.use("/v1", externalRouter);
